name: Go Build and Release

on:
  push:
    branches:
      - "[GO] Release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: |
          go build -ldflags "-s -w -X main.version=${GITHUB_REF#refs/heads/} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date +%Y-%m-%d)" -trimpath -o logz

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Compress with UPX
        run: |
          upx ./logz --force-overwrite --lzma --no-progress --no-color

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ./logz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
