name: Go Build and Release

on:
  push:
    branches:
      - "release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: |
          make build

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ./logz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
